### ISSUE TITLE
分表不应该是垂直拆分字段吗 为何ds0库中order0 order1 俩个表的字段都是一样的 不应该是俩个表字段累加成同一个表吗？

### ISSUE THREAD

**Issue by Garlichead** [FleyX/demo-project#1]
分表不应该是垂直拆分字段吗 为何ds0库中order0 order1 俩个表的字段都是一样的 不应该是俩个表字段累加成同一个表吗

**Comment by FleyX** [comment]
这里的分表指的是水平拆分，在分库基础上再分一次表，减少单表数据量。

**Comment by Garlichead** [comment]
拆分了库 然后不同的库存不同的数据量 但是不同库中表的字段是一样的 同一个库中俩个表的字段一样 存不同的数据
